# Generated by Django 2.0.1 on 2018-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_auto_20180131_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.AddField(
            model_name='author',
            name='pob',
            field=models.CharField(default='india', max_length=20),
        ),
    ]
