# Generated by Django 2.0.1 on 2018-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_auto_20180202_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='dob',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
