# Generated by Django 2.0.1 on 2018-02-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_auto_20180204_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_info',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pob', models.CharField(default='india', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('age', models.IntegerField(default=25)),
            ],
        ),
        migrations.DeleteModel(
            name='author',
        ),
    ]
